# Pandas Project Exercise - Solutions

# The Data

This data set contains booking information for a city hotel and a resort hotel, and includes information such as when the booking was made, length of stay, the number of adults, children, and/or babies, and the number of available parking spaces, among other things.

All personally identifying information has been removed from the data.

Acknowledgements
The data is originally from the article Hotel Booking Demand Datasets, written by Nuno Antonio, Ana Almeida, and Luis Nunes for Data in Brief, Volume 22, February 2019.


----------------------------

#### NOTE: Names, Emails, Phone Numbers, and Credit Card numbers in the data are synthetic and not real information from people. The hotel data is real from the publication listed above.

## <div style="text-align: center">Data Column Reference</div>

In [1]:
import pandas as pd

In [2]:
hotels = pd.read_csv("C:\\Users\\ARUNKUMAR\\Downloads\\UNZIP_FOR_NOTEBOOKS_FINAL\\03-Pandas\\hotel_booking_data.csv")
hotels.shape

(119390, 36)

In [3]:
hotels.info()

<class 'pandas.DataFrame'>
RangeIndex: 119390 entries, 0 to 119389
Data columns (total 36 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   hotel                           119390 non-null  str
 1   is_canceled                     119390 non-null  int64
 2   lead_time                       119390 non-null  int64
 3   arrival_date_year               119390 non-null  int64
 4   arrival_date_month              119390 non-null  str
 5   arrival_date_week_number        119390 non-null  int64
 6   arrival_date_day_of_month       119390 non-null  int64
 7   stays_in_weekend_nights         119390 non-null  int64
 8   stays_in_week_nights            119390 non-null  int64
 9   adults                          119390 non-null  int64
 10  children                        119386 non-null  float64
 11  babies                          119390 non-null  int64
 12  meal                            119390 non-null  str
 13  country                         118902 non-null  str
 14  market_segment                  119390 non-null  str
 15  distribution_channel            119390 non-null  str
 16  is_repeated_guest               119390 non-null  int64
 17  previous_cancellations          119390 non-null  int64
 18  previous_bookings_not_canceled  119390 non-null  int64
 19  reserved_room_type              119390 non-null  str
 20  assigned_room_type              119390 non-null  str
 21  booking_changes                 119390 non-null  int64
 22  deposit_type                    119390 non-null  str
 23  agent                           103050 non-null  float64
 24  company                         6797 non-null    float64
 25  days_in_waiting_list            119390 non-null  int64
 26  customer_type                   119390 non-null  str
 27  adr                             119390 non-null  float64
 28  required_car_parking_spaces     119390 non-null  int64
 29  total_of_special_requests       119390 non-null  int64
 30  reservation_status              119390 non-null  str
 31  reservation_status_date         119390 non-null  str
 32  name                            119390 non-null  str
 33  email                           119390 non-null  str
 34  phone-number                    119390 non-null  str
 35  credit_card                     119390 non-null  str
dtypes: float64(4), int64(16), str(16)
memory usage: 32.8 MB

# TASK: How many rows are there?

In [4]:
len(hotels)

119390

# TASK: Is there any missing data? If so, which column has the most missing data?

In [5]:
hotels.isnull().sum()

hotel                                  0
is_canceled                            0
lead_time                              0
arrival_date_year                      0
arrival_date_month                     0
arrival_date_week_number               0
arrival_date_day_of_month              0
stays_in_weekend_nights                0
stays_in_week_nights                   0
adults                                 0
children                               4
babies                                 0
meal                                   0
country                              488
market_segment                         0
distribution_channel                   0
is_repeated_guest                      0
previous_cancellations                 0
previous_bookings_not_canceled         0
reserved_room_type                     0
assigned_room_type                     0
booking_changes                        0
deposit_type                           0
agent                              16340
company                           112593
days_in_waiting_list                   0
customer_type                          0
adr                                    0
required_car_parking_spaces            0
total_of_special_requests              0
reservation_status                     0
reservation_status_date                0
name                                   0
email                                  0
phone-number                           0
credit_card                            0
dtype: int64

# TASK: Drop the "company" column from the dataset.

In [6]:
hotels = hotels.drop('company',axis=1)

In [7]:
hotels.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,customer_type,adr,required_car_parking_spaces,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,Transient,0.0,0,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157

**TASK: What are the top 5 most common country codes in the dataset?**

In [8]:
hotels['country'].value_counts().head(5)

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: count, dtype: int64

In [9]:
hotels['country'].value_counts()[:5]

country
PRT    48590
GBR    12129
FRA    10415
ESP     8568
DEU     7287
Name: count, dtype: int64

# TASK: What is the name of the person who paid the highest ADR (average daily rate)? How much was their ADR?

In [10]:
hotels.columns

Index(['hotel', 'is_canceled', 'lead_time', 'arrival_date_year',
       'arrival_date_month', 'arrival_date_week_number',
       'arrival_date_day_of_month', 'stays_in_weekend_nights',
       'stays_in_week_nights', 'adults', 'children', 'babies', 'meal',
       'country', 'market_segment', 'distribution_channel',
       'is_repeated_guest', 'previous_cancellations',
       'previous_bookings_not_canceled', 'reserved_room_type',
       'assigned_room_type', 'booking_changes', 'deposit_type', 'agent',
       'days_in_waiting_list', 'customer_type', 'adr',
       'required_car_parking_spaces', 'total_of_special_requests',
       'reservation_status', 'reservation_status_date', 'name', 'email',
       'phone-number', 'credit_card'],
      dtype='str')

In [11]:
highest_adr = hotels.sort_values('adr', ascending=False)

In [12]:
highest_adr[['name','adr']].head()

                  name     adr
48515    Daniel Walter  5400.0
111403     Jesus Mason   510.0
15083   Samuel Hammond   508.0
103912  Jessica Morris   451.5
13142        Amy Banks   450.0

In [13]:
highest_adr[['name','adr']].iloc[0]

name    Daniel Walter
adr            5400.0
Name: 48515, dtype: object

In [14]:
hotels['adr'].idxmax()

48515

In [15]:
hotels.iloc[hotels['adr'].idxmax()]

hotel                                             City Hotel
is_canceled                                                1
lead_time                                                 35
arrival_date_year                                       2016
arrival_date_month                                     March
arrival_date_week_number                                  13
arrival_date_day_of_month                                 25
stays_in_weekend_nights                                    0
stays_in_week_nights                                       1
adults                                                     2
children                                                 0.0
babies                                                     0
meal                                                      BB
country                                                  PRT
market_segment                                 Offline TA/TO
distribution_channel                                   TA/TO
is_repeated_guest                                          0
previous_cancellations                                     0
previous_bookings_not_canceled                             0
reserved_room_type                                         A
assigned_room_type                                         A
booking_changes                                            1
deposit_type                                      Non Refund
agent                                                   12.0
days_in_waiting_list                                       0
customer_type                                      Transient
adr                                                   5400.0
required_car_parking_spaces                                0
total_of_special_requests                                  0
reservation_status                                  Canceled
reservation_status_date                           2016-02-19
name                                           Daniel Walter
email                             DanielWalter27@comcast.net
phone-number                                    865-280-5832
credit_card                                 ************6075
Name: 48515, dtype: object

In [16]:
hotels.iloc[48515]

hotel                                             City Hotel
is_canceled                                                1
lead_time                                                 35
arrival_date_year                                       2016
arrival_date_month                                     March
arrival_date_week_number                                  13
arrival_date_day_of_month                                 25
stays_in_weekend_nights                                    0
stays_in_week_nights                                       1
adults                                                     2
children                                                 0.0
babies                                                     0
meal                                                      BB
country                                                  PRT
market_segment                                 Offline TA/TO
distribution_channel                                   TA/TO
is_repeated_guest                                          0
previous_cancellations                                     0
previous_bookings_not_canceled                             0
reserved_room_type                                         A
assigned_room_type                                         A
booking_changes                                            1
deposit_type                                      Non Refund
agent                                                   12.0
days_in_waiting_list                                       0
customer_type                                      Transient
adr                                                   5400.0
required_car_parking_spaces                                0
total_of_special_requests                                  0
reservation_status                                  Canceled
reservation_status_date                           2016-02-19
name                                           Daniel Walter
email                             DanielWalter27@comcast.net
phone-number                                    865-280-5832
credit_card                                 ************6075
Name: 48515, dtype: object

# TASK: The adr is the average daily rate for a person's stay at the hotel. What is the mean adr across all the hotel stays in the dataset?

In [17]:
round(hotels['adr'].mean(),2)

np.float64(101.83)

## TASK: What is the average (mean) number of nights for a stay across the entire data set? Feel free to round this to 2 decimal points. ##

In [18]:
# data shows weekend night and week night

In [19]:
hotels['total_stay_nights'] = hotels['stays_in_week_nights'] + hotels['stays_in_weekend_nights']
round(hotels['total_stay_nights'].mean(),2)

np.float64(3.43)

## TASK: What is the average total cost for a stay in the dataset? Not average daily cost, but total stay cost. Feel free to round this to 2 decimal points.##

In [20]:
# average daily rate of a person multiplies with week nights and weekend nights

In [21]:
hotels['avg_total_cost'] = hotels['adr'] * hotels['total_stay_nights']

In [22]:
round(hotels['avg_total_cost'].mean(),2)

np.float64(357.85)

## TASK: What are the names and emails of people who made 5 "Special Requests"?

In [23]:
hotels[hotels['total_of_special_requests'] == 5][['name','email']]

                          name                          email
7860             Amanda Harper           Amanda.H66@yahoo.com
11125            Laura Sanders      Sanders_Laura@hotmail.com
14596              Tommy Ortiz            Tommy_O@hotmail.com
14921           Gilbert Miller         Miller.Gilbert@aol.com
14922           Timothy Torres         TTorres@protonmail.com
24630          Jennifer Weaver             Jennifer_W@aol.com
27288           Crystal Horton             Crystal.H@mail.com
27477           Brittney Burke       Burke_Brittney16@att.com
29906          Cynthia Cabrera    Cabrera.Cynthia@xfinity.com
29949              Sarah Floyd              Sarah_F@gmail.com
32267           Michelle Villa         Michelle.Villa@aol.com
39027           Nichole Hebert       Hebert.Nichole@gmail.com
39129         Lindsey Mckenzie       Lindsey.Mckenzie@att.com
39525           Ashley Edwards       Edwards.Ashley@yahoo.com
70114       Christopher Torres   Torres.Christopher@gmail.com
78819   Mrs. Tara Sullivan DVM           Mrs..DVM@xfinity.com
78820           Michaela Brown          MichaelaBrown@att.com
78822        Kurt Maldonado MD              KMD15@xfinity.com
97072         Jason Richardson               Jason.R@zoho.com
97099             Terri Hurley            THurley@xfinity.com
97261        Mrs. Caitlin Webb             Mrs._W@comcast.net
98410             Holly Arroyo          Arroyo_Holly@mail.com
98674          Denise Campbell             Denise_C@gmail.com
99887            Michael Smith            Michael.S42@aol.com
99888       Dr. Trevor Sellers                  Dr._S@aol.com
101569            Kayla Murphy         Kayla.Murphy@yahoo.com
102061         Taylor Martinez    Taylor.Martinez@hotmail.com
109511          Charles Wilson       Charles_Wilson@yahoo.com
109590           Tyler Allison         Tyler.A@protonmail.com
110082          Matthew Bailey         Matthew_Bailey@aol.com
110083       Charlotte Acevedo        Charlotte_A@verizon.com
111909         Darrell Brennan  Brennan_Darrell51@hotmail.com
111911          Melinda Jensen         MelindaJensen@zoho.com
113915            Terry Arnold          Arnold.Terry@zoho.com
114770             Mary Nguyen     Nguyen.Mary@protonmail.com
114909          Lindsay Cuevas      Lindsay.Cuevas40@mail.com
116455       Cynthia Hernandez   CynthiaHernandez@xfinity.com
116457          Angela Hawkins             Angela_H@gmail.com
118817              Sue Lawson            Sue.L52@comcast.net
119161         Alyssa Richards        Alyssa_Richards@aol.com

## TASK: What percentage of hotel stays were classified as "repeat guests"? (Do not base this off the name of the person, but instead of the is_repeated_guest column)

In [24]:
hotels['is_repeated_guest'].value_counts()

is_repeated_guest
0    115580
1      3810
Name: count, dtype: int64

In [25]:
percentage = sum(hotels['is_repeated_guest'] == 1)/len(hotels) *100
percentage

3.191222045397437

## TASK: What are the top 5 most common last name in the dataset? Bonus: Can you figure this out in one line of pandas code? (For simplicity treat the a title such as MD as a last name, for example Caroline Conley MD can be said to have the last name MD)
##

In [26]:
hotels['name']

0              Ernest Barnes
1               Andrea Baker
2             Rebecca Parker
3               Laura Murray
4                Linda Hines
                 ...
119385       Claudia Johnson
119386        Wesley Aguilar
119387          Mary Morales
119388    Caroline Conley MD
119389        Ariana Michael
Name: name, Length: 119390, dtype: str

In [36]:
def grablastname (name):
    return name.split()[-1]

In [38]:
hotels['name'].apply(grablastname).value_counts()

name
Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
            ...
Riggs         23
Weeks         23
Bolton        22
IV            22
V             10
Name: count, Length: 1009, dtype: int64

In [27]:
hotels['name'].apply (lambda name: name.split()[-1])

0          Barnes
1           Baker
2          Parker
3          Murray
4           Hines
           ...
119385    Johnson
119386    Aguilar
119387    Morales
119388         MD
119389    Michael
Name: name, Length: 119390, dtype: str

In [29]:
most_common = hotels['name'].apply (lambda name: name.split()[-1]).value_counts()
most_common

name
Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
            ...
Riggs         23
Weeks         23
Bolton        22
IV            22
V             10
Name: count, Length: 1009, dtype: int64

In [35]:
most_common.sort_values(ascending = False).head()

name
Smith       2503
Johnson     1990
Williams    1618
Jones       1434
Brown       1423
Name: count, dtype: int64

## TASK: What are the names of the people who had booked the most number children and babies for their stay? (Don't worry if they canceled, only consider number of people reported at the time of their reservation)

In [45]:
 hotels['babies'].unique()

array([ 0,  1,  2, 10,  9])

In [42]:
hotels['total_kids'] = hotels['babies'] + hotels['children']
hotels.head(2)

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,total_stay_nights,avg_total_cost,total_kids
0,Resort Hotel,0,342,2015,July,27,1,0,0,2,...,0,Check-Out,2015-07-01,Ernest Barnes,Ernest.Barnes31@outlook.com,669-792-1661,************4322,0,0.0,0.0
1,Resort Hotel,0,737,2015,July,27,1,0,0,2,...,0,Check-Out,2015-07-01,Andrea Baker,Andrea_Baker94@aol.com,858-637-6955,************9157,0,0.0,0.0

In [47]:
hotels.sort_values('total_kids', ascending=False)[['name','total_kids']]

                   name  total_kids
328       Jamie Ramirez        10.0
46619   Nicholas Parker        10.0
78656     Marc Robinson         9.0
6681     Nicolas Thomas         3.0
16360       Ashley Cole         3.0
...                 ...         ...
119389   Ariana Michael         0.0
40600      Craig Campos         NaN
40667      David Murphy         NaN
40679      Frank Burton         NaN
41160     Jerry Roberts         NaN

[119390 rows x 2 columns]

## TASK: What are the top 3 most common area code in the phone numbers? (Area code is first 3 digits)

In [66]:
hotels['phone-number'].apply(lambda num: num[:3]).value_counts()

phone-number
799    168
185    167
541    166
137    163
739    163
      ...
896    106
973    105
577    105
818    102
970     97
Name: count, Length: 900, dtype: int64

In [67]:
hotels['phone-number'].apply(lambda num: num[:3]).value_counts()[:3]

phone-number
799    168
185    167
541    166
Name: count, dtype: int64

In [64]:
hotels[hotels['phone-number'].astype(str).str.startswith('799', na=False)]

,hotel,is_canceled,lead_time,arrival_date_year,arrival_date_month,arrival_date_week_number,arrival_date_day_of_month,stays_in_weekend_nights,stays_in_week_nights,adults,...,total_of_special_requests,reservation_status,reservation_status_date,name,email,phone-number,credit_card,total_stay_nights,avg_total_cost,total_kids
1556,Resort Hotel,1,1,2015,September,36,4,0,1,2,...,0,Canceled,2015-09-04,Alejandro Davis,ADavis@gmail.com,799-447-4301,************4217,1,117.90,0.0
1586,Resort Hotel,1,74,2015,September,36,5,2,4,2,...,0,Canceled,2015-06-29,Robert Byrd,Robert.Byrd@comcast.net,799-139-5203,************6817,6,858.00,0.0
1608,Resort Hotel,0,356,2015,September,36,5,4,10,2,...,0,Check-Out,2015-09-19,Stacy Strong,Strong_Stacy69@yandex.com,799-844-6626,************8372,14,1284.78,0.0
1716,Resort Hotel,0,111,2015,September,37,10,2,7,2,...,0,Check-Out,2015-09-19,Amy White,Amy.White58@gmail.com,799-913-3616,************6488,9,913.50,0.0
2323,Resort Hotel,1,78,2015,October,41,9,1,2,2,...,0,Canceled,2015-08-14,Nicole Williams,Nicole_W@zoho.com,799-674-4056,************7738,3,276.00,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115653,City Hotel,0,95,2017,July,27,6,0,3,2,...,1,Check-Out,2017-07-09,Tracey Ross,TraceyRoss@yahoo.com,799-103-5448,************1784,3,360.00,0.0
116533,City Hotel,0,78,2017,July,29,19,0,3,2,...,1,Check-Out,2017-07-22,Anthony Smith,Anthony.S82@xfinity.com,799-179-3957,************9774,3,273.60,0.0
117009,City Hotel,0,350,2017,July,30,24,1,4,2,...,2,Check-Out,2017-07-29,Barbara Pacheco,Barbara_P@gmail.com,799-250-0531,************3551,5,445.50,0.0
119041,City Hotel,0,71,2017,August,34,26,1,1,1,...,1,Check-Out,2017-08-28,Stephanie Nicholson,Stephanie.N@yahoo.com,799-508-1056,************6061,2,328.00,0.0
119085,City Hotel,0,518,2017,August,34,26,2,1,2,...,1,Check-Out,2017-08-29,Melissa Escobar,MEscobar@aol.com,799-841-4516,************4393,3,338.01,0.0

## TASK: How many arrivals took place between the 1st and the 15th of the month (inclusive of 1 and 15) ? Bonus: Can you do this in one line of pandas code?

In [71]:
arrivals_took_place = hotels['arrival_date_day_of_month'].apply(lambda day: day in range(1,16)).sum()
arrivals_took_place

np.int64(58152)

## HARD BONUS TASK: Create a table for counts for each day of the week that people arrived. (E.g. 5000 arrivals were on a Monday, 3000 were on a Tuesday, etc..)

In [84]:
import numpy as np

In [92]:
def convert (day,month,year):
    return f"{day}-{month}-{year}"

In [93]:
hotels['date'] = np.vectorize(convert)(hotels['arrival_date_day_of_month'],hotels['arrival_date_month'],hotels['arrival_date_year'])

In [94]:
hotels['date']

0            1-July-2015
1            1-July-2015
2            1-July-2015
3            1-July-2015
4            1-July-2015
               ...
119385    30-August-2017
119386    31-August-2017
119387    31-August-2017
119388    31-August-2017
119389    29-August-2017
Name: date, Length: 119390, dtype: str

In [96]:
hotels['date'] = pd.to_datetime(hotels['date'])
hotels['date']

0        2015-07-01
1        2015-07-01
2        2015-07-01
3        2015-07-01
4        2015-07-01
            ...
119385   2017-08-30
119386   2017-08-31
119387   2017-08-31
119388   2017-08-31
119389   2017-08-29
Name: date, Length: 119390, dtype: datetime64[us]

In [99]:
hotels['date'].dt.day_name()

0         Wednesday
1         Wednesday
2         Wednesday
3         Wednesday
4         Wednesday
            ...
119385    Wednesday
119386     Thursday
119387     Thursday
119388     Thursday
119389      Tuesday
Name: date, Length: 119390, dtype: str

In [98]:
hotels['date'].dt.day_name().value_counts()

date
Friday       19631
Thursday     19254
Monday       18171
Saturday     18055
Wednesday    16139
Sunday       14141
Tuesday      13999
Name: count, dtype: int64